### ISSUE TITLE
[EPIC] uc-001-a Loginvorgang

### ISSUE THREAD

**Issue by cbrgm** [zerkaner/litmgmt#1]
1. Der Anwender gibt Name und Passwort ein.
2. Beides wird an den Server übertragen und dort verifiziert.
3. Bei erfolgreicher Verifizierung wird der Anwender angemeldet. Ansonsten
wird wieder Schritt 1 ausgeführt.

**Comment by zerkaner** [comment]
Serverseitig vorbereitet. Endpunkte /api/register und /api/login stehen bereit.
